name: "Release Tag Validator"
description: "Validate release tags and delete invalid ones"
author: "loilo"

runs:
  using: "composite"
  steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: "v2.x"

    - name: Validate tag
      shell: bash
      run: deno run --allow-run --allow-read --allow-env ${GITHUB_ACTION_PATH}/script.ts
