name: "Release Tag Validator"
description: "Validate release tags and delete invalid ones"
author: "loilo"

inputs:
  tag-name:
    description: "Tag to validate"
    required: true
  commit-sha:
    description: "SHA of the commit"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: "v2.x"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 10 # Optimize fetch performance while keeping recent rcN tags
    
    - name: Ensure all tags are fetched
      run: git fetch --unshallow --tags

    - name: Validate tag
      shell: bash
      run: deno run --allow-run --allow-read ${GITHUB_ACTION_PATH}/script.ts ${{ inputs.tag-name }} ${{ inputs.commit-sha }}
