name: "Release Tag Validator"
description: "Validate release tags and delete invalid ones"
author: "loilo"

runs:
  using: "composite"
  steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: "v2.x"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Set `fetch-depth: 0` so we can retrieve rcN tags

    - name: Validate tag
      shell: bash
      run: deno run --allow-run --allow-env script.ts
