name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Run fmt
        run: |
          deno fmt --check
      - name: Run lint
        run: |
          deno lint
      - name: Run tests
        run: |
          deno test -A --coverage=.coverage
      - name: Create coverage report
        run: "deno coverage ./.coverage --lcov > ./.coverage/coverage.lcov"
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./.coverage/coverage.lcov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
